#! bin/bash
my_help () {
    echo "------------------------------------------"
    echo "| command list"
    echo "|   run"
    echo "|   start"
    echo "|   rm"
    echo "|   update"
    echo "|   help"
    echo "------------------------------------------"
    echo "| run"
    echo "|   use ide in language list"
    echo "| start"
    echo "|   start container in langage list"
    echo "| images"
    echo "|   show images in langage list"
    echo "| ps"
    echo "|   show container in langage list"
    echo "| rm"
    echo "|   rm container in langage list"
    echo "| update"
    echo "|   update all ide in language list"
    echo "| help"
    echo "|   show help"
    echo "------------------------------------------"
    echo "| language list"
    echo "|   python"
    echo "|   typescript"
    echo "------------------------------------------"
}
